#!/usr/bin/env python3
"""Validate HTML Preview files generated by html-show agent."""

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass, field
from pathlib import Path


REQUIRED_SECTIONS_PRD = [
    "Overview",
    "Scope",
    "Flow",
    "States",
    "Rules",
    "Acceptance",
    "Assumptions",
]

FORBIDDEN_PATTERNS = {
    "endpoint detail": re.compile(r"\b(GET|POST|PUT|PATCH|DELETE)\s+/api\b", re.IGNORECASE),
    "database DDL": re.compile(r"\b(CREATE\s+TABLE|ALTER\s+TABLE|DROP\s+TABLE)\b", re.IGNORECASE),
    "migration detail": re.compile(r"\bmigration\b|数据库表|建表|迁移", re.IGNORECASE),
    "code type": re.compile(r"\b(pub\s+struct|interface\s+\w+|type\s+\w+\s*=)\b"),
    "schema detail": re.compile(r"请求参数表|响应字段表|HTTP\s*状态码|schema", re.IGNORECASE),
}

EXTERNAL_DEPENDENCY_PATTERNS = {
    "external script": re.compile(r"<script[^>]+src\s*=", re.IGNORECASE),
    "external stylesheet": re.compile(r"<link[^>]+rel=[\"']?stylesheet", re.IGNORECASE),
    "cdn reference": re.compile(r"https?://|//cdn\.|unpkg\.com|jsdelivr\.net", re.IGNORECASE),
    "module import": re.compile(r"\bimport\s+.*\s+from\s+[\"']", re.IGNORECASE),
}

PRD_PROFILE = {
    "required_sections": REQUIRED_SECTIONS_PRD,
    "forbidden_patterns": FORBIDDEN_PATTERNS,
}


@dataclass
class PreviewResult:
    source_doc: str
    preview: str
    doc_type: str = "generic"
    ok: bool = True
    issues: list[str] = field(default_factory=list)

    def fail(self, message: str) -> None:
        self.ok = False
        self.issues.append(message)


def find_prd_files(root: Path, feature: str | None) -> list[Path]:
    prd_root = root / "docs" / "prd"
    if not prd_root.exists():
        return []

    files = [path for path in prd_root.rglob("*.md") if path.name != "00-index.md"]
    if feature and feature != "--all":
        normalized = feature.lower()
        files = [
            path
            for path in files
            if path.stem.lower() == normalized or normalized in path.stem.lower()
        ]
    return sorted(files)


def detect_doc_type(source_path: Path, root: Path) -> str:
    try:
        relative = source_path.relative_to(root)
        parts = relative.parts
        if len(parts) >= 3 and parts[0] == "docs" and parts[1] == "prd":
            return "prd"
    except ValueError:
        pass
    return "generic"


def derive_preview_path(source_path: Path, root: Path) -> Path:
    try:
        relative = source_path.relative_to(root)
        parts = relative.parts
        if len(parts) >= 4 and parts[0] == "docs" and parts[1] == "prd":
            domain = parts[2]
            return root / ".ai" / "preview" / domain / source_path.with_suffix(".html").name
    except ValueError:
        pass
    return root / ".ai" / "preview" / source_path.with_suffix(".html").name


def validate_preview(source_path: Path, root: Path, doc_type: str | None = None) -> PreviewResult:
    relative = source_path.relative_to(root)
    detected_type = doc_type or detect_doc_type(source_path, root)
    preview_path = derive_preview_path(source_path, root)

    result = PreviewResult(
        source_doc=relative.as_posix(),
        preview=preview_path.relative_to(root).as_posix(),
        doc_type=detected_type,
    )

    if not preview_path.exists():
        result.fail("missing HTML Preview")
        return result

    html = preview_path.read_text(encoding="utf-8", errors="replace")
    source = str(relative).replace("\\", "/")

    # Generic checks
    if "<!doctype html" not in html.lower():
        result.fail("missing <!doctype html>")
    if "<style" not in html.lower():
        result.fail("missing inline CSS")

    has_doc_source = "data-doc-source" in html
    has_prd_source = "data-prd-source" in html
    if not has_doc_source and not has_prd_source:
        result.fail("missing data-doc-source or data-prd-source")
    if source not in html.replace("\\", "/"):
        result.fail(f"missing source document path: {source}")

    for name, pattern in EXTERNAL_DEPENDENCY_PATTERNS.items():
        if pattern.search(html):
            result.fail(f"external dependency detected: {name}")

    # PRD profile checks
    if detected_type == "prd":
        profile = PRD_PROFILE

        for section in profile["required_sections"]:
            if section not in html:
                result.fail(f"missing required section: {section}")
            doc_marker = f'data-doc-section="{section}"'
            prd_marker = f'data-prd-section="{section}"'
            if doc_marker not in html and prd_marker not in html:
                result.fail(f"missing section marker: {section}")

        for name, pattern in profile["forbidden_patterns"].items():
            if pattern.search(html):
                result.fail(f"forbidden content detected: {name}")

        has_example_data = re.search(r"示例|sample|example", html, re.IGNORECASE)
        if has_example_data and "示例数据，不是接口契约" not in html:
            result.fail("sample data appears without required disclaimer")

    return result


def main() -> int:
    parser = argparse.ArgumentParser(description="Validate HTML Preview files.")
    parser.add_argument("target", nargs="?", default="--all", help="Feature name, file path, or --all")
    parser.add_argument("--root", default=".", help="Target project root, defaults to current directory")
    parser.add_argument("--type", choices=["prd", "generic"], default=None, help="Document type (auto-detect if not specified)")
    parser.add_argument("--json", action="store_true", help="Print machine-readable JSON")
    args = parser.parse_args()

    root = Path(args.root).resolve()

    # Determine source files
    target_path = root / args.target if args.target != "--all" else None
    if target_path and target_path.exists() and target_path.suffix.lower() == ".md":
        source_files = [target_path]
    else:
        source_files = find_prd_files(root, args.target)

    results = [validate_preview(path, root, args.type) for path in source_files]
    summary = {
        "checked": len(results),
        "passed": sum(1 for item in results if item.ok),
        "failed": sum(1 for item in results if not item.ok),
        "results": [item.__dict__ for item in results],
    }

    if args.json:
        print(json.dumps(summary, ensure_ascii=False, indent=2))
    else:
        print(f"HTML Preview check: {summary['passed']}/{summary['checked']} passed")
        for item in results:
            status = "PASS" if item.ok else "FAIL"
            print(f"[{status}] {item.preview} (type: {item.doc_type})")
            for issue in item.issues:
                print(f"  - {issue}")

    return 0 if summary["failed"] == 0 and summary["checked"] > 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
